Cms.Web/Controllers/BlogAdminController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Cms.Data.Contexts.Blog;
using Cms.Data.Model;
using System.Linq;
using System.Collections.Generic;

namespace Cms.Web.Controllers
{
    [Authorize]
    public class BlogAdminController : Controller
    {
        private readonly IBlogDbContext _db;

        public BlogAdminController(IBlogDbContext db)
        {
            _db = db;
        }

        public async Task<ActionResult> Index()
        {
            return View(await _db.Posts.OrderByDescending(o => o.PostedOn).ToListAsync());
        }

        public ActionResult Create()
        {
            ViewBag.AvailableCategories = GetAailableCategories();

            Post post = new Post();
            post.PostedOn = System.DateTime.Now;

            return View(post);
        }

        [AdminAuthorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,ShortDescription,Content,UrlSlug,NewCategory,NewTags,Published,PostedOn,ModifiedOn")] Post post)
        {
            if (ModelState.IsValid)
            {
                post.Category = (await _db.Categories.FirstOrDefaultAsync(c => c.Name.Equals(post.NewCategory, System.StringComparison.CurrentCultureIgnoreCase)) 
                                ?? new Category { Name = post.NewCategory, UrlSlug = post.NewCategory.ToLower().Replace(" ", "-"), Description = post.NewCategory });

                if (post.Category.Id == 0)
                {
                    _db.Categories.Add(post.Category);
                    _db.Entry(post.Category).State = EntityState.Added;
                    await _db.SaveChangesAsync();
                }

                post.CategoryId = post.Category.Id;
                _db.Posts.Add(post);
                await _db.SaveChangesAsync();

                if (!string.IsNullOrWhiteSpace(post.NewTags))
                {
                    post.Tags = post.NewTags.Split(new string[] { "," }, System.StringSplitOptions.RemoveEmptyEntries).Select(s => new Tag { Name = s.Trim(), Description = s.Trim(), UrlSlug = s.Trim().ToLower().Replace(" ", "-"), Post = post }).ToList();
                    await _db.SaveChangesAsync();
                }

                return RedirectToAction("Index");
            }

            ViewBag.AvailableCategories = GetAailableCategories();

            return View(post);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Post post = await _db.Posts.FindAsync(id);
            if (post == null)
            {
                return HttpNotFound();
            }

            ViewBag.AvailableCategories = GetAailableCategories();

            post.ModifiedOn = System.DateTime.Now;
            post.NewCategory = post.Category.Name;
            _db.Entry(post).Collection("Tags").Load();
            post.NewTags = string.Join(", ", post.Tags.Select(s => s.Name).OrderBy(o => o));

            return View(post);
        }

        [AdminAuthorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,ShortDescription,Content,UrlSlug,NewCategory,NewTags,Published,PostedOn,ModifiedOn")] Post post)
        {
            ViewBag.AvailableCategories = GetAailableCategories();

            if (ModelState.IsValid)
            {
                post.ModifiedOn = System.DateTime.Now;
                post.Category = (await _db.Categories.FirstOrDefaultAsync(c => c.Name.Equals(post.NewCategory, System.StringComparison.CurrentCultureIgnoreCase))
                                ?? new Category { Name = post.NewCategory, UrlSlug = post.NewCategory.ToLower().Replace(" ", "-"), Description = post.NewCategory });

                if (post.Category.Id == 0)
                {
                    _db.Categories.Add(post.Category);
                    _db.Entry(post.Category).State = EntityState.Added;
                    await _db.SaveChangesAsync();
                }

                post.CategoryId = post.Category.Id;
                _db.Entry(post).State = EntityState.Modified;
                await _db.SaveChangesAsync();

                var newTags = new List<Tag>();
                if (!string.IsNullOrWhiteSpace(post.NewTags))
                {
                    newTags = post.NewTags.Split(new string[] { "," }, System.StringSplitOptions.RemoveEmptyEntries).Select(s => new Tag { Name = s.Trim(), Description = s.Trim(), UrlSlug = s.Trim().ToLower().Replace(" ", "-"), Post = post }).ToList();
                }
                var tagNames = newTags.Select(s => s.Name);
                _db.Tags.RemoveRange(_db.Tags.Where(t => t.Post.Id == post.Id && !tagNames.Contains(t.Name)));
                newTags.RemoveAll(t => _db.Tags.Any(a => a.Post.Id == post.Id && a.Name == t.Name));
                _db.Tags.AddRange(newTags);
                await _db.SaveChangesAsync();

                _db.Entry(post).Collection("Tags").Load();
                post.NewTags = string.Join(", ", post.Tags.Select(s => s.Name).OrderBy(o => o).ToList());

                return View(post);
            }

            return View(post);
        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = await _db.Posts.FindAsync(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        [AdminAuthorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            _db.Tags.RemoveRange(_db.Tags.Where(t => t.Post.Id == id));
            Post post = await _db.Posts.FindAsync(id);
            _db.Posts.Remove(post);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private string GetAailableCategories()
        {
            IEnumerable<string> categories = _db.Categories.ToList().Select(s => s.Name).Distinct().OrderBy(o => o);
            categories = categories.Select(s => "<a href='#' onclick=\"$('#NewCategory').val('" + s + "');return false;\">" + s + "</a>");
            return string.Join("<span>, </span>", categories);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cms.Web/Views/BlogAdmin/Create.cshtml
@model Cms.Data.Model.Post

@{
    ViewBag.Title = "Create";
}


@section PageBanner {
    <div>
        <h1>
            Create Post
        </h1>
    </div>
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control", style = "height: 100px" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control", style = "height: 250px" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="NewCategory" class="control-label col-md-2">Available Categories</label>
            <div class="col-md-10">
                @MvcHtmlString.Create(ViewBag.AvailableCategories)
            </div>
        </div>

        <div class="form-group">
            <label for="NewCategory" class="control-label col-md-2">Category</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewCategory, new { htmlAttributes = new { @class = "form-control", id = "NewCategory" } })
                @Html.ValidationMessageFor(model => model.NewCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="NewTags" class="control-label col-md-2">Tags</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewTags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewTags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="Published" class="control-label col-md-2">Publish</label>
            <div class="col-md-10" style="font-size: 1.7em; color: #999">
                @Html.EditorFor(model => model.Published)
                @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index", "BlogAdmin")" class="btn btn-default">Cancel</a> &nbsp; 
                <input type="submit" value="Create" class="btn btn-success"/>
            </div>
        </div>
    </div>
}

Cms.Web/Views/BlogAdmin/Delete.cshtml
@model Cms.Data.Model.Post

@{
    ViewBag.Title = "Delete";
}


@section PageBanner {
    <div>
        <h1>
            Delete Post
        </h1>
    </div>
}

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrlSlug)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrlSlug)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <a href="@Url.Action("Index", "BlogAdmin")" class="btn btn-default">Cancel</a> &nbsp;
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

Cms.Web/Views/BlogAdmin/Edit.cshtml
@model Cms.Data.Model.Post

@{
    ViewBag.Title = "Edit";
}


@section PageBanner {
    <div>
        <h1>
            Update Post
        </h1>
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control", style = "height: 100px" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control", style = "height: 250px" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="NewCategory" class="control-label col-md-2">Available Categories</label>
            <div class="col-md-10">
                @MvcHtmlString.Create(ViewBag.AvailableCategories)
            </div>
        </div>

        <div class="form-group">
            <label for="NewCategory" class="control-label col-md-2">Category</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewCategory, new { htmlAttributes = new { @class = "form-control", id = "NewCategory" } })
                @Html.ValidationMessageFor(model => model.NewCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="NewTags" class="control-label col-md-2">Tags</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewTags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewTags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="Published" class="control-label col-md-2">Publish</label>
            <div class="col-md-10" style="font-size: 1.7em; color: #999">
                @Html.EditorFor(model => model.Published)
                @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index", "BlogAdmin")" class="btn btn-default">Cancel</a> &nbsp;
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cms.Web/Views/BlogAdmin/Index.cshtml
@model IEnumerable<Cms.Data.Model.Post>

@{
    ViewBag.Title = "Blog CMS";
}

@section PageBanner {
    <div>
        <h1>
            Manage Posts
        </h1>
    </div>
}

<p>
    <a href="@Url.Action("Create", "BlogAdmin")" class="btn btn-primary">Create Post &nbsp; <i class="fa fa-plus-square fa-1_1x"></i></a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrlSlug)
        </th>
        <th style="width: 120px">
            @Html.DisplayNameFor(model => model.PostedOn)
        </th>
        <th style="width: 100px">Actions</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UrlSlug)
        </td>
        <td>
            @item.PostedOn.ToString("dd-MM-yyyy")
        </td>
        <td>
            <a href="@Url.Action("Edit", "BlogAdmin", new { id = item.Id })" class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-pencil"></span></a>
            <a href="@Url.Action("Delete", "BlogAdmin", new { id = item.Id })" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
        </td>
    </tr>
}

</table>