Cms.Web/Controllers/GdriveAdminController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Cms.Data.Contexts.Gdrive;
using Cms.Data.Model;
using System.Web;
using System.IO;
using System.Linq;

namespace Cms.Web.Controllers
{
    [Authorize]
    public class GdriveAdminController : Controller
    {
        private GdriveDbContext db = new GdriveDbContext();

        public async Task<ActionResult> Index()
        {
            return View(await db.Files.Where(x => x.SecurityCode == "AB10E95").OrderByDescending(o => o.UploadedOn).ToListAsync());
        }

        public ActionResult Create()
        {
            return View();
        }

        [AdminAuthorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,SecurityCode")] FileContent fileContent, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    fileContent.FileName = file.FileName;
                    using (var binaryReader = new BinaryReader(file.InputStream))
                    {
                        fileContent.Content = binaryReader.ReadBytes(file.ContentLength);
                    }
                }

                fileContent.UploadedOn = System.DateTime.Now;
                db.Files.Add(fileContent);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(fileContent);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FileContent fileContent = await db.Files.FindAsync(id);
            if (fileContent == null)
            {
                return HttpNotFound();
            }
            return View(fileContent);
        }

        [AdminAuthorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,SecurityCode")] FileContent fileContent, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    fileContent.FileName = file.FileName;
                    using (var binaryReader = new BinaryReader(file.InputStream))
                    {
                        fileContent.Content = binaryReader.ReadBytes(file.ContentLength);
                    }
                }

                fileContent.UploadedOn = System.DateTime.Now;
                db.Entry(fileContent).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(fileContent);
        }

        public async Task<ActionResult> Download(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FileContent fileContent = await db.Files.FindAsync(id);
            if (fileContent == null)
            {
                return HttpNotFound();
            }
            return File(fileContent.Content, GetContentType(fileContent.FileName), fileContent.FileName);
        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FileContent fileContent = await db.Files.FindAsync(id);
            if (fileContent == null)
            {
                return HttpNotFound();
            }
            return View(fileContent);
        }

        [AdminAuthorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            FileContent fileContent = await db.Files.FindAsync(id);
            db.Files.Remove(fileContent);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private string GetContentType(string fileName)
        {
            var ext = fileName.Substring(fileName.LastIndexOf('.') + 1).ToUpper();
            switch (ext)
            {
                case "JPG":
                case "JPEG":
                    return "image/jpeg";

                case "PNG":
                    return "image/png";

                case "ZIP":
                    return "application/zip";

                default:
                    return "application/octet";
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cms.Web/Views/GdriveAdmin/Create.cshtml
@model Cms.Data.Model.FileContent

@{
    ViewBag.Title = "Create";
}

@section PageBanner {
    <div>
        <h1>
            Upload File
        </h1>
    </div>
}

@using (Html.BeginForm("Create", "GdriveAdmin", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SecurityCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecurityCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Upload File
            <div class="col-md-10">
                <input type="file" name="file" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index", "GdriveAdmin")" class="btn btn-default">Cancel</a> &nbsp;
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cms.Web/Views/GdriveAdmin/Delete.cshtml
@model Cms.Data.Model.FileContent

@{
    ViewBag.Title = "Delete";
}

@section PageBanner {
    <div>
        <h1>
            Delete File
        </h1>
    </div>
}


<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UploadedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UploadedOn)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <a href="@Url.Action("Index", "GdriveAdmin")" class="btn btn-default">Cancel</a> &nbsp;
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

Cms.Web/Views/GdriveAdmin/Edit.cshtml
@model Cms.Data.Model.FileContent

@{
    ViewBag.Title = "Edit";
}

@section PageBanner {
    <div>
        <h1>
            Update File
        </h1>
    </div>
}


@using (Html.BeginForm("Edit", "GdriveAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SecurityCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecurityCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Upload File
            <div class="col-md-10">
                <input type="file" name="file" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index", "GdriveAdmin")" class="btn btn-default">Cancel</a> &nbsp;
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cms.Web/Views/GdriveAdmin/Index.cshtml
@model IEnumerable<Cms.Data.Model.FileContent>

@{
    ViewBag.Title = "Drive CMS";
}

@section PageBanner {
    <div>
        <h1>
            Manage Files
        </h1>
    </div>
}

<p>
    <a href="@Url.Action("Create", "GdriveAdmin")" class="btn btn-primary">Upload File &nbsp; <i class="fa fa-plus-square fa-1_1x"></i></a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SecurityCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th style="width: 150px">
            @Html.DisplayNameFor(model => model.UploadedOn)
        </th>
        <th style="width: 150px">Actions</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @if (item.SecurityCode == "AB10E95")
            {
                @Html.DisplayFor(modelItem => item.SecurityCode)
            }
            else
            {
                <span>******</span>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        <td>
            @item.UploadedOn.Value.ToString("dd-MM-yyyy")
        </td>
        <td>
            <a href="@Url.Action("Download", "GdriveAdmin", new { id = item.Id })" class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-download"></span></a>
            @*<a href="@Url.Action("Edit", "GdriveAdmin", new { id = item.Id })" class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-pencil"></span></a>*@
            <a href="@Url.Action("Delete", "GdriveAdmin", new { id = item.Id })" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
        </td>
    </tr>
}

</table>